### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by GiverPlay007** [GiverPlay007/YetAnotherRaceCarGame#1]
**Tasks**

---

- [ ] **Game basics**
  - [x] Logo Scene
  - [ ] Road Scene
  - [ ] Lobby Scene
  - [x] Assets
  - [x] Cars (entity system)
  - [ ] Game Over

---

- [ ] Cars
  - [ ] Upgrades
  - [ ] Change colors

---

- [ ] **Road Scene**
  - [ ] Infinity scrolling background
  - [ ] Cars spawn and destroy
  - [ ] Collision with cars
  - [ ] Increment game speed based on late game

---

- [ ] **Lobby Scene**
  - [ ] Change cars
  - [ ] Purchase cars
  - [ ] Purchase roads
  - [ ] Customize cars

**Comment by GiverPlay007** [comment]
Projeto descontinuado
